<?php
/*
#####################################
#  ShopOS: Скрипты интернет-магазина
#  Copyright (c) 2008-2009
# http://www.shopos.ru
# Ver. 1.0.0
#####################################
*/

define('MODULE_PAYMENT_TYPE_PERMISSION', 'cod');
define('MODULE_PAYMENT_COD_TEXT_TITLE', 'Nachnahme');
define('MODULE_PAYMENT_COD_TEXT_DESCRIPTION', 'Nachnahme');

define('MODULE_PAYMENT_COD_TEXT_INFO', '');
define('MODULE_PAYMENT_COD_STATUS_TITLE', 'Nachnahme Modul aktivieren');
define('MODULE_PAYMENT_COD_STATUS_DESC', 'M&ouml;chten Sie Zahlungen per Nachnahme akzeptieren?');


define('MODULE_PAYMENT_COD_COST_TITLE', _MODULES_PAYMENT_FEE_TITLE);
define('MODULE_PAYMENT_COD_COST_DESC', _MODULES_PAYMENT_FEE_DESC);
define('MODULE_PAYMENT_COD_ZONE_TITLE', _MODULES_ZONE_TITLE);
define('MODULE_PAYMENT_COD_ZONE_DESC', _MODULES_ZONE_DESC);
define('MODULE_PAYMENT_COD_ALLOWED_TITLE', _MODULES_ZONE_ALLOWED_TITLE);
define('MODULE_PAYMENT_COD_ALLOWED_DESC', _MODULES_ZONE_ALLOWED_DESC);
define('MODULE_PAYMENT_COD_SORT_ORDER_TITLE', _MODULES_SORT_ORDER_TITLE);
define('MODULE_PAYMENT_COD_SORT_ORDER_DESC', _MODULES_SORT_ORDER_DESC);
define('MODULE_PAYMENT_COD_ORDER_STATUS_ID_TITLE', _MODULES_SET_ORDER_STATUS_TITLE);
define('MODULE_PAYMENT_COD_ORDER_STATUS_ID_DESC', _MODULES_SET_ORDER_STATUS_DESC);
?>