<?php
/*
#####################################
#  ShopOS: Скрипты интернет-магазина
#  Copyright (c) 2008-2009
# http://www.shopos.ru
# Ver. 1.0.0
#####################################
*/

define('MODULE_SHIPPING_SELFPICKUP_TEXT_TITLE', 'Selbstabholung');
define('MODULE_SHIPPING_SELFPICKUP_TEXT_DESCRIPTION', 'Selbstabholung der Ware in unserer Geschдftsstelle');
define('MODULE_SHIPPING_SELFPICKUP_SORT_ORDER', 'Sortierung');

define('MODULE_SHIPPING_SELFPICKUP_TEXT_TITLE', 'Selbstabholung.');
define('MODULE_SHIPPING_SELFPICKUP_TEXT_WAY', 'Selbstabholung der Ware in unserer Gesch&auml;ftsstelle.');
define('MODULE_SHIPPING_SELFPICKUP_STATUS_TITLE', 'Selbstabholung aktivieren');
define('MODULE_SHIPPING_SELFPICKUP_STATUS_DESC', 'M&ouml;chten Sie Selbstabholung anbieten?');


define('MODULE_SHIPPING_SELFPICKUP_TAX_CLASS_TITLE' , _MODULES_TAX_ZONE_TITLE);
define('MODULE_SHIPPING_SELFPICKUP_TAX_CLASS_DESC' ,_MODULES_TAX_ZONE_DESC);
define('MODULE_SHIPPING_SELFPICKUP_ZONE_TITLE' , _MODULES_ZONE_TITLE);
define('MODULE_SHIPPING_SELFPICKUP_ZONE_DESC' , _MODULES_ZONE_DESC);
define('MODULE_SHIPPING_SELFPICKUP_SORT_ORDER_TITLE' , _MODULES_SORT_ORDER_TITLE);
define('MODULE_SHIPPING_SELFPICKUP_SORT_ORDER_DESC' , _MODULES_SORT_ORDER_DESC);
define('MODULE_SHIPPING_SELFPICKUP_ALLOWED_TITLE' , _MODULES_ZONE_ALLOWED_TITLE);
define('MODULE_SHIPPING_SELFPICKUP_ALLOWED_DESC' , _MODULES_ZONE_ALLOWED_DESC);
define('MODULE_SHIPPING_SELFPICKUP_INVALID_ZONE', _MODULE_INVALID_SHIPPING_ZONE);
define('MODULE_SHIPPING_SELFPICKUP_UNDEFINED_RATE', _MODULE_UNDEFINED_SHIPPING_RATE);
?>