<?
/*
#####################################
#  ShopOS: Скрипты интернет-магазина
#  Copyright (c) 2008-2009
# http://www.shopos.ru
# Ver. 1.0.0
#####################################
*/

define('MODULE_PAYMENT_INVOICE_TEXT_DESCRIPTION', 'Rechnung');
define('MODULE_PAYMENT_INVOICE_TEXT_TITLE', 'Rechnung');
define('MODULE_PAYMENT_INVOICE_TEXT_INFO', '');
define('MODULE_PAYMENT_INVOICE_STATUS_TITLE', 'Rechnungsmodul aktivieren');
define('MODULE_PAYMENT_INVOICE_STATUS_DESC', 'M&ouml;chten Sie Zahlungen per Invoices akzeptieren?');
define('MODULE_PAYMENT_INVOICE_MIN_ORDER_TITLE', 'Notwendige Bestellungen');
define('MODULE_PAYMENT_INVOICE_MIN_ORDER_DESC', 'Die Mindestanzahl an Bestellungen die ein Kunden haben muss damit die Option zur Verfьgung steht.');

define('MODULE_PAYMENT_INVOICE_COST_TITLE', _MODULES_PAYMENT_FEE_TITLE);
define('MODULE_PAYMENT_INVOICE_COST_DESC', _MODULES_PAYMENT_FEE_DESC);
define('MODULE_PAYMENT_INVOICE_ZONE_TITLE', _MODULES_ZONE_TITLE);
define('MODULE_PAYMENT_INVOICE_ZONE_DESC', _MODULES_ZONE_DESC);
define('MODULE_PAYMENT_INVOICE_ALLOWED_TITLE', _MODULES_ZONE_ALLOWED_TITLE);
define('MODULE_PAYMENT_INVOICE_ALLOWED_DESC', _MODULES_ZONE_ALLOWED_DESC);
define('MODULE_PAYMENT_INVOICE_SORT_ORDER_TITLE', _MODULES_SORT_ORDER_TITLE);
define('MODULE_PAYMENT_INVOICE_SORT_ORDER_DESC', _MODULES_SORT_ORDER_DESC);
define('MODULE_PAYMENT_INVOICE_ORDER_STATUS_ID_TITLE', _MODULES_SET_ORDER_STATUS_TITLE);
define('MODULE_PAYMENT_INVOICE_ORDER_STATUS_ID_DESC', _MODULES_SET_ORDER_STATUS_DESC);
?>